Resources:
  DDBConsumedWriteCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProdOrStaging
    Properties:
      AlarmName: ${opt:stage, 'local'}-mex-backend-ddb-write-capacity-alarm
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ProvisionedWriteCapacityUnits
      Namespace: AWS/DynamoDB
      Period: 60
      Statistic: Average
      Threshold: 15
      AlarmActions:
        - !Ref DDBAlarmsSNS
      Dimensions:
        - Name: TableName
          Value: !If [IsProd, !Ref mexDataProd, !Ref mexDataTest]
      Tags:
        - Key: "Name"
          Value: "${opt:stage, 'local'}-mex-backend-ddb-write-capacity-alarm"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "alarm"
        - Key: "ResourceContext"
          Value: "ddb-write-capacity-alarm"
        - Key: "Owner"
          Value: "varun"


  DDBConsumedReadCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProdOrStaging
    Properties:
      AlarmName: ${opt:stage, 'local'}-mex-backend-ddb-read-capacity-alarm
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ProvisionedWriteCapacityUnits
      Namespace: AWS/DynamoDB
      Period: 60
      Statistic: Average
      Threshold: 35
      AlarmActions:
        - !Ref DDBAlarmsSNS
      Dimensions:
        - Name: TableName
          Value: !If [IsProd, !Ref mexDataProd, !Ref mexDataTest]
      Tags:
        - Key: "Name"
          Value: "${opt:stage, 'local'}-mex-backend-ddb-read-capacity-alarm"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "alarm"
        - Key: "ResourceContext"
          Value: "ddb-read-capacity-alarm"
        - Key: "Owner"
          Value: "varun"


  DDBReadThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProdOrStaging
    Properties:
      AlarmName: ${opt:stage, 'local'}-mex-backend-ddb-read-throttle-alarm
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ReadThrottleEvents
      Namespace: AWS/DynamoDB
      Period: 60
      Statistic: Sum
      Threshold: 1
      AlarmActions:
        - !Ref DDBAlarmsSNS
      Dimensions:
        - Name: TableName
          Value: !If [IsProd, !Ref mexDataProd, !Ref mexDataTest]
      Tags:
        - Key: "Name"
          Value: "${opt:stage, 'local'}-mex-backend-ddb-read-throttle-alarm"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "alarm"
        - Key: "ResourceContext"
          Value: "ddb-read-throttle-alarm"
        - Key: "Owner"
          Value: "varun"


  DDBWriteThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProdOrStaging
    Properties:
      AlarmName: ${opt:stage, 'local'}-mex-backend-ddb-write-throttle-alarm
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: WriteThrottleEvents
      Namespace: AWS/DynamoDB
      Period: 60
      Statistic: Sum
      Threshold: 1
      AlarmActions:
        - !Ref DDBAlarmsSNS
      Dimensions:
        - Name: TableName
          Value: !If [IsProd, !Ref mexDataProd, !Ref mexDataTest]
      Tags:
        - Key: "Name"
          Value: "${opt:stage, 'local'}-mex-backend-ddb-write-throttle-alarm"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "alarm"
        - Key: "ResourceContext"
          Value: "ddb-write-throttle-alarm"
        - Key: "Owner"
          Value: "varun"

