Resources:
  DDBConsumedWriteCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProdOrStaging
    Properties:
      AlarmName: ${opt:stage, 'local'}-mex-backend-ddb-write-capacity-alarm
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ProvisionedWriteCapacityUnits
      Namespace: AWS/DynamoDB
      Period: 60
      Statistic: Average
      Threshold: 15
      AlarmActions:
        - !Ref DDBAlarmsSNS
      Dimensions:
        - Name: TableName
          Value: !If [IsProd, !Ref mexDDBProd, !Ref mexDataTest]


  DDBConsumedReadCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProdOrStaging
    Properties:
      AlarmName: ${opt:stage, 'local'}-mex-backend-ddb-read-capacity-alarm
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ProvisionedWriteCapacityUnits
      Namespace: AWS/DynamoDB
      Period: 60
      Statistic: Average
      Threshold: 35
      AlarmActions:
        - !Ref DDBAlarmsSNS
      Dimensions:
        - Name: TableName
          Value: !If [IsProd, !Ref mexDDBProd, !Ref mexDataTest]


  DDBReadThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProdOrStaging
    Properties:
      AlarmName: ${opt:stage, 'local'}-mex-backend-ddb-read-throttle-alarm
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: ReadThrottleEvents
      Namespace: AWS/DynamoDB
      Period: 60
      Statistic: Sum
      Threshold: 1
      AlarmActions:
        - !Ref DDBAlarmsSNS
      Dimensions:
        - Name: TableName
          Value: !If [IsProd, !Ref mexDDBProd, !Ref mexDataTest]


  DDBWriteThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProdOrStaging
    Properties:
      AlarmName: ${opt:stage, 'local'}-mex-backend-ddb-write-throttle-alarm
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: WriteThrottleEvents
      Namespace: AWS/DynamoDB
      Period: 60
      Statistic: Sum
      Threshold: 1
      AlarmActions:
        - !Ref DDBAlarmsSNS
      Dimensions:
        - Name: TableName
          Value: !If [IsProd, !Ref mexDDBProd, !Ref mexDataTest]