Resources:
  PublicNoteElasticCacheCluster: # we only create a redis cache cluster for non prod environment through this config
    Type: AWS::ElastiCache::ReplicationGroup
    Condition: IsDefaultOrStaging
    Properties:
      ReplicationGroupId: mex-public-note-cache-${opt:stage, self:provider.stage}
      ReplicationGroupDescription: "Redis cache cluster"
      MultiAZEnabled: true
      AutomaticFailoverEnabled: true
      AutoMinorVersionUpgrade: true
      Engine: redis
      CacheNodeType: cache.t3.micro
      NumCacheClusters: 3
      SecurityGroupIds:
        - sg-51d4667f
      CacheSubnetGroupName: mex-public-note-cache-subnet