Resources:
  ElasticCacheCluster:
    DependsOn: LambdaSecurityGroup
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: true
      Engine: redis
      CacheNodeType: cache.t3.small
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - "Fn::GetAtt": LambdaSecurityGroup.GroupId
      CacheSubnetGroupName:
        Ref: ElasticCacheSubnetGroup