Resources:
  PublicNoteElasticCacheCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: mex-cache-${opt:stage, self:provider.stage}
      ReplicationGroupDescription: "Redis cache cluster"
      MultiAZEnabled: true
      AutomaticFailoverEnabled: true
      AutoMinorVersionUpgrade: true
      Engine: redis
      CacheNodeType: cache.t3.micro
      NumCacheClusters: 3
      SecurityGroupIds:
        - sg-51d4667f
      CacheSubnetGroupName: !Ref PrivateSubnetGroup