Resources:
  PublicNoteElasticCacheCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: "Public note cache cluster"
      AutomaticFailoverEnabled: true
      AutoMinorVersionUpgrade: true
      Engine: redis
      CacheNodeType: cache.t3.small
      NumCacheClusters: 2
      SecurityGroupIds:
        - "Fn::GetAtt": LambdaSecurityGroup.GroupId
      CacheSubnetGroupName:
        Ref: ElasticCacheSubnetGroup