Resources:
  PublicNote:
    Type: "AWS::SQS::Queue"
    Condition: IsDefaultOrStaging
    Properties:
      QueueName: public-note-${opt:stage, self:provider.stage}.fifo
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "PublicNoteDLQ"
            - "Arn"
        maxReceiveCount: 5
      # AWS recommendation to set the visibility timeout as 6 times as the lambda's timeout
      VisibilityTimeout: 180
  PublicNoteDLQ:
    Type: "AWS::SQS::Queue"
    Condition: IsDefaultOrStaging
    Properties:
      QueueName: public-note-dlq-${opt:stage, self:provider.stage}.fifo
      FifoQueue: true
  NamespaceDelete:
    Type: "AWS::SQS::Queue"
    Condition: IsDefaultOrStaging
    Properties:
      QueueName: namespace-delete-${opt:stage, self:provider.stage}.fifo
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "NamespaceDeleteDLQ"
            - "Arn"
        maxReceiveCount: 3
      VisibilityTimeout: 120
  NamespaceDeleteDLQ:
    Type: "AWS::SQS::Queue"
    Condition: IsDefaultOrStaging
    Properties:
      QueueName: namespace-delete-dlq-${opt:stage, self:provider.stage}.fifo
      FifoQueue: true
  NodeDelete:
    Type: "AWS::SQS::Queue"
    Condition: IsDefaultOrStaging
    Properties:
      QueueName: node-delete-${opt:stage, self:provider.stage}.fifo
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "NodeDeleteDLQ"
            - "Arn"
        maxReceiveCount: 3
      VisibilityTimeout: 120
  NodeDeleteDLQ:
    Type: "AWS::SQS::Queue"
    Condition: IsDefaultOrStaging
    Properties:
      QueueName: node-delete-dlq-${opt:stage, self:provider.stage}.fifo
      FifoQueue: true