Resources:
  PublicNote:
    Type: "AWS::SQS::Queue"
    Condition: IsProd
    Properties:
      QueueName: ${opt:stage, self:provider.stage}-mex-backend-public-note-queue
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "PublicNoteDLQ"
            - "Arn"
        maxReceiveCount: 3
      # AWS recommendation to set the visibility timeout as 6 times as the lambda's timeout
      VisibilityTimeout: 120
      Tags:
        - Key: "Name"
          Value: "${opt:stage, self:provider.stage}-mex-backend-public-note-queue"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "queue"
        - Key: "ResourceContext"
          Value: "public-note-queue"
        - Key: "Owner"
          Value: "varun"



  PublicNoteDLQ:
    Type: "AWS::SQS::Queue"
    Condition: IsProd
    Properties:
      QueueName: ${opt:stage, self:provider.stage}-mex-backend-public-note-dlq
      FifoQueue: true
      Tags:
        - Key: "Name"
          Value: "${opt:stage, self:provider.stage}-mex-backend-public-note-queue"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "dlq"
        - Key: "ResourceContext"
          Value: "public-note-dlq"
        - Key: "Owner"
          Value: "varun"

  NamespaceDelete:
    Type: "AWS::SQS::Queue"
    Condition: IsProd
    Properties:
      QueueName: ${opt:stage, self:provider.stage}-mex-backend-namespace-delete-queue
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "NamespaceDeleteDLQ"
            - "Arn"
        maxReceiveCount: 3
      VisibilityTimeout: 120
      Tags:
        - Key: "Name"
          Value: "${opt:stage, self:provider.stage}-mex-backend-namespace-delete-queue"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "queue"
        - Key: "ResourceContext"
          Value: "namespace-delete-queue"
        - Key: "Owner"
          Value: "varun"

  NamespaceDeleteDLQ:
    Type: "AWS::SQS::Queue"
    Condition: IsProd
    Properties:
      QueueName: ${opt:stage, self:provider.stage}-mex-backend-namespace-delete-dlq
      FifoQueue: true
      Tags:
        - Key: "Name"
          Value: "${opt:stage, self:provider.stage}-mex-backend-namespace-delete-dlq"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "dlq"
        - Key: "ResourceContext"
          Value: "namespace-delete-dlq"
        - Key: "Owner"
          Value: "varun"


  NodeDelete:
    Type: "AWS::SQS::Queue"
    Condition: IsProd
    Properties:
      QueueName: ${opt:stage, self:provider.stage}-mex-backend-node-delete-queue
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "NodeDeleteDLQ"
            - "Arn"
        maxReceiveCount: 3
      VisibilityTimeout: 120
      Tags:
        - Key: "Name"
          Value: "${opt:stage, self:provider.stage}-mex-backend-node-delete-queue"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "queue"
        - Key: "ResourceContext"
          Value: "node-delete-queue"
        - Key: "Owner"
          Value: "varun"



  NodeDeleteDLQ:
    Type: "AWS::SQS::Queue"
    Condition: IsProd
    Properties:
      QueueName: ${opt:stage, self:provider.stage}-mex-backend-node-delete-dlq
      FifoQueue: true
      Tags:
        - Key: "Name"
          Value: "${opt:stage, self:provider.stage}-mex-backend-public-note-queue"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "dlq"
        - Key: "ResourceContext"
          Value: "node-delete-dlq"
        - Key: "Owner"
          Value: "varun"