Resources:
  DDBStreamSNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: 'DLQ Notification - ${opt:stage, self:provider.stage}' # Email Subject
      TopicName: dlq-sns-${opt:stage, self:provider.stage}
      Subscription:
        - Endpoint: "dlq-sns-aaaai5b2qhovh5vuzszayhinre@workduck-workspace.slack.com" #dlq-sns slack channel
          Protocol: "email"
  DDBAlarmsSNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: 'DDB Notification - ${opt:stage, self:provider.stage}' # Email Subject
      TopicName: ddb-alarms-mex-${opt:stage, self:provider.stage}
      Subscription:
        - Endpoint: "ddb-alarms-aaaaiul5sicbiorxwhkybvam4a@workduck-workspace.slack.com"
          Protocol: "email"