Resources:
  DDBStreamSNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${opt:stage, self:provider.stage}-mex-backend-dlq-sns
      DisplayName: 'DLQ Notification - ${opt:stage, self:provider.stage}' # Email Subject
      Subscription:
        - Endpoint: "dlq-sns-aaaai5b2qhovh5vuzszayhinre@workduck-workspace.slack.com" #dlq-sns slack channel
          Protocol: "email"
      Tags:
        - Key: "Name"
          Value: "${opt:stage, self:provider.stage}-mex-backend-dlq-sns"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "sns"
        - Key: "ResourceContext"
          Value: "dlq-sns"
        - Key: "Owner"
          Value: "varun"

  DDBAlarmsSNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${opt:stage, self:provider.stage}-mex-backend-ddb-alarm-sns
      DisplayName: 'DDB Notification - ${opt:stage, self:provider.stage}' # Email Subject
      Subscription:
        - Endpoint: "ddb-alarms-aaaaiul5sicbiorxwhkybvam4a@workduck-workspace.slack.com" #ddb-alarms slack channel
          Protocol: "email"
      Tags:
        - Key: "Name"
          Value: "${opt:stage, self:provider.stage}-mex-backend-alarm-sns"
        - Key: "Environment"
          Value: "prod"
        - Key: "Component"
          Value: "mex-backend"
        - Key: "ResourceType"
          Value: "sns"
        - Key: "ResourceContext"
          Value: "ddb-alarm-sns"
        - Key: "Owner"
          Value: "varun"

#Resources:
#  DDBStreamSNS:
#    Type: AWS::SNS::Topic
#    Properties:
#      DisplayName: 'DLQ Notification - ${opt:stage, self:provider.stage}' # Email Subject
#      TopicName: dlq-sns-${opt:stage, self:provider.stage}
#      Subscription:
#        - Endpoint: "dlq-sns-aaaai5b2qhovh5vuzszayhinre@workduck-workspace.slack.com" #dlq-sns slack channel
#          Protocol: "email"
#  DDBAlarmsSNS:
#    Type: AWS::SNS::Topic
#    Properties:
#      DisplayName: 'DDB Notification - ${opt:stage, self:provider.stage}' # Email Subject
#      TopicName: ddb-alarms-mex-${opt:stage, self:provider.stage}
#      Subscription:
#        - Endpoint: "ddb-alarms-aaaaiul5sicbiorxwhkybvam4a@workduck-workspace.slack.com"
#          Protocol: "email"