name: CI/CD for Kotlin Project

on:
  push:
    branches:
      - WD-1780

env:
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS Lambda
        run: sls deploy --aws-profile default -stage=test

#      - name: serverless deploy
#        uses: serverless/github-action@v3.1
#        with:
#          args: deploy --stage test
#      - name: Install Serverless Framework
#        uses: actions/cache@v2
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
#        run: npm install -g serverless
#
#      - name: Deploy to AWS Lambda
#        run: sls deploy --aws-profile -stage=test
